### PR TITLE
Rescue signal exception

### LINKED ISSUE #32: Gruf::Server doesn't handle signals
It appears that all signal handling logic was removed from `GRPC::RpcServer` and server now simply crashes when process is killed:

`Ctrl+C`

```console
I, [2017-10-27T12:59:43.326558 #87078]  INFO -- : Booting gRPC Server...
I, [2017-10-27T12:59:43.329951 #87078]  INFO -- : handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::V1::Health::Service#check>
^C
bundler: failed to load command: gruf (/Users/user/.rbenv/versions/2.4.1/bin/gruf)
Interrupt:
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.6.6-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:370:in `request_call'
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.6.6-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:370:in `loop_handle_server_calls'
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.6.6-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:331:in `run'
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gruf-2.0.1/lib/gruf/server.rb:63:in `start!'
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gruf-2.0.1/bin/gruf:27:in `<top (required)>'
  /Users/user/.rbenv/versions/2.4.1/bin/gruf:22:in `load'
  /Users/user/.rbenv/versions/2.4.1/bin/gruf:22:in `<top (required)>
```

`SIGTERM`

```console
I, [2017-10-27T12:59:43.326558 #87078]  INFO -- : Booting gRPC Server...
I, [2017-10-27T12:59:43.329951 #87078]  INFO -- : handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::V1::Health::Service#check>
bundler: failed to load command: gruf (/Users/user/.rbenv/versions/2.4.1/bin/gruf)
SignalException: SIGTERM
  /Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grpc-1.6.6-universal-darwin/src/ruby/lib/grpc/generic/rpc_server.rb:370:in `request_call'
```

With this monkey-patch `Ctrl+C` and `SIGTERM` are handled properly.

```ruby
Gruf::Server.class_eval do
  alias_method :orig_start!, :start!

  def start!
    orig_start!
  rescue Interrupt, SignalException, SystemExit
    logger.info { 'Shutting down gRPC server...' }
    server.stop
  end
end
```

```console
I, [2017-10-27T12:59:43.326558 #87078]  INFO -- : Booting gRPC Server...
I, [2017-10-27T12:59:43.329951 #87078]  INFO -- : handling /grpc.health.v1.Health/Check with #
^C
I, [2017-10-27T13:01:14.288286 #87184]  INFO -- : Shutting down gRPC server...
I, [2017-10-27T13:01:14.288537 #87184]  INFO -- : stopping, will wait for all the workers to exit
I, [2017-10-27T13:01:14.290172 #87184]  INFO -- : schedule another job
I, [2017-10-27T13:01:14.292240 #87184]  INFO -- : stopped, all workers are shutdown
```

Can I submit a PR to rescue these exceptions in `Gruf::Server` so we can remove this patch from all of our services or am I missing something here?

### PR DESCRIPTION
**Pull request by Parad0X**
## What? Why?

Fixes #32 

## How was it tested?

Spec + extensive testing in production

### CODE REVIEW

File: lib/gruf/server.rb [hunk 1]
```diff
@@ -61,7 +61,9 @@ def server
     def start!
       logger.info { 'Booting gRPC Server...' }
       server.run_till_terminated
+    rescue Interrupt, SignalException, SystemExit
```
Comment (splittingred) [inline lib/gruf/server.rb]: Can you wrap this method in `# rubocop:disable Lint/ShadowedException` and `# rubocop:enable Lint/ShadowedException` flags? (May need to rebase this from master)

Comment (Parad0X) [reply lib/gruf/server.rb]: 👍  updated

**Comment by splittingred** [comment]
Thanks for this! I'll cut a 2.0.2 release now.

**Comment by Parad0X** [comment]
@splittingred :shipit: !

**Comment by splittingred** [comment]
@Parad0X https://rubygems.org/gems/gruf/versions/2.0.2 🙇

**Comment by Parad0X** [comment]
@splittingred Thank you for taking care of this so fast. `bundle update`!
